### ISSUE TITLE
Add drop_sequence_index parameter to fit function

### ISSUE THREAD

**Issue by HarisNaveed17** [sdv-dev/DeepEcho#23]
* DeepEcho version: 0.1.3
* Python version: 3.8.5
* Operating System: Ubuntu 16.04.6

### Description
After the data is generated. I want to keep the sequence index in it as well. I see that the parameter drop_sequence_index is already present but defaults to True. I see no way to change it since the parameter cannot be passed through either the PARModel instance or the fit function.

**Comment by csala** [comment]
Hello @HarisNaveed17 thanks for the suggestion and the interest to contribute this, but I think change should not be necessary.

DeepEcho is not intended to be used as a standalone package, but rather as a modeling engine within [SDV](https://sdv.dev/SDV), which provides additional functionalities, including proper sequence index modeling.

So I suggest you to use the `sdv.timeseries.PAR` model instead of the `PARModel` from this package. You will find all the documentation for the `PAR` class here: https://sdv.dev/SDV/user_guides/timeseries/par.html

**Comment by HarisNaveed17** [comment]
Yeah I found it a few minutes after posting here and started using it. Thanks!
